# Titulo 1
## Titulo 2
### Titulo 3

**Este es mi texto en negrita**
 
__Este es mi texto 2 en negrita__

*Esto es cursiva*

_Esto es cursiva 2_

1. Elemento numero 1
2. Elemento numero 2 
3. Elemento numero 3

## Receta del arroz con pollo

- Arroz
- Pollo
- Ensalada
- Aceite

![arroz con pollo] (https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQiFPDdDnlynOO5URCASCtaTwH30qW6rFIug&s)

